# Generated by Django 4.0 on 2021-12-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancienSujet', '0003_departement_faculte_filiere_niveau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to='documents'),
        ),
    ]
